properly throw errors so Catch node can handle them.
smchamberlin/node-red-contrib-ibm-db2 pull request #21
Opened 2018-12-19 00:37 UTC by rophy

Currently dashdb node doesn't properly handle errors - it logs the error on console, then "swallows" it.

Impact: when errors happened in dashdb nodes, the flow simply terminates and there is no way for flow developer to handle error and recover.

The proper way to handle errors as documented in node-red [official docs](https://nodered.org/docs/writing-functions#handling-errors):

## Handling errors

If the function encounters an error that should halt the current flow, it should return nothing. To trigger a Catch node on the same tab, the function should call node.error with the original message as a second argument:

```javascript
node.error("hit an error", msg);
```

This PR updates dashdb code to pass in `msg` in all `node.error()` calls so that Catch node will be able to catch those errors.

2019-01-21 07:51 UTC, smchamberlin reviewed
trophy, sorry for the late reply.

I haven't heard of this catch node before.  Thank you for making the effort to update the code to collaborate with this framework.

Have you tested your changes to make sure they work as they should?  And nothing breaks?

Thanks

2019-01-25 02:01 UTC, rophy commented
@smchamberlin I have been using the patched version in my project for a month and it worked fine so far.

In terms of "breaking changes", there is one thing worth mentioning:

when errors happen, the node need to decide whether:

1. throw an exception or not (which should get caught by Catch node)
2. continue to send outputs, or terminate the message flow

The PR added (1) in all error workflows, which is fine.
But in terms of (2), in current master branch, it is inconsistent on whether the node sends output or not.
For example, https://github.com/smchamberlin/node-red-nodes-cf-sqldb-dashdb/blob/master/98-sqldb-dashdb-cf.js#L115 terminates the flow and send nothing, while https://github.com/smchamberlin/node-red-nodes-cf-sqldb-dashdb/blob/master/98-sqldb-dashdb-cf.js#L353 sets msg.error but continue to send an output of `msg.payload = null`.

The PR tries to be consistent that the node "terminates the flow" in all error cases, but this can be a breaking changes if a workflow assumes the node will always send output in https://github.com/smchamberlin/node-red-nodes-cf-sqldb-dashdb/blob/master/98-sqldb-dashdb-cf.js#L353 even when error happens.

Do you have any thoughts on what we want to define behavior in the case of (2) ?

2020-10-02 07:04 UTC, smchamberlin requested changes
It looks good, just have one question where a try/catch was removed. Thanks!

2020-10-02 07:04 UTC, smchamberlin commented on 98-sqldb-dashdb-cf.js
> -      try {
Why did you remove the try/catch here ?

2026-06-19 09:42 UTC, closed without merging